In [1]:
import warnings
import pandas as pd

warnings.filterwarnings("ignore")

## Merge original dataset with discharge notes features

In [2]:
discharge_htn_features_df = pd.read_csv("../data/processed/discharge_htn_features.csv")
final_hosp_dataset_df = pd.read_csv("../data/processed/final_hosp_dataset.csv")

# Use LEFT JOIN to keep all rows from the hosp dataset
final_hosp_discharge_df = pd.merge(
    final_hosp_dataset_df,
    discharge_htn_features_df,
    on='subject_id',
    how='left'   # 👈 keeps all subjects from final_hosp_dataset_df
)

print(final_hosp_dataset_df.shape)
print(final_hosp_discharge_df.shape)
final_hosp_discharge_df.head()

(36899, 23)
(36899, 27)

,subject_id,gender,anchor_age,label,has_labs,has_omr,has_charte,Anion_Gap_mean,Bicarbonate_mean,Chloride_mean,...,Glucose_min,weight_kg_mean,height_cm_mean,bmi_mean,bp_sys_mean,bp_dia_mean,htn_any_mention,htn_mention_count,htn_first_mention_time,htn_last_mention_time
0,10000032,F,52,0,1,1,1,11.222222,25.388889,97.047619,...,71.0,42.231264,152.40000,18.5375,106.166667,64.666667,True,3.0,2180-05-07,2180-05-07
1,10000068,F,19,0,0,0,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,10000084,M,72,0,1,1,1,12.833333,23.166667,100.666667,...,88.0,77.110703,177.80000,24.4000,NaN,NaN,NaN,NaN,NaN,NaN
3,10000108,M,25,0,1,0,1,15.000000,29.000000,101.000000,...,88.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,10000117,F,48,0,1,1,1,16.928571,23.714286,102.533333,...,73.0,50.407558,163.98875,18.5480,114.805556,71.847222,True,2.0,2181-11-15,2183-09-21

In [3]:
final_hosp_discharge_df = final_hosp_discharge_df.drop(columns=['htn_first_mention_time', 'htn_last_mention_time'])

In [4]:
print(final_hosp_discharge_df.shape)
final_hosp_discharge_df.head()

(36899, 25)

,subject_id,gender,anchor_age,label,has_labs,has_omr,has_charte,Anion_Gap_mean,Bicarbonate_mean,Chloride_mean,...,Glucose_std,Glucose_max,Glucose_min,weight_kg_mean,height_cm_mean,bmi_mean,bp_sys_mean,bp_dia_mean,htn_any_mention,htn_mention_count
0,10000032,F,52,0,1,1,1,11.222222,25.388889,97.047619,...,19.343071,155.0,71.0,42.231264,152.40000,18.5375,106.166667,64.666667,True,3.0
1,10000068,F,19,0,0,0,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,10000084,M,72,0,1,1,1,12.833333,23.166667,100.666667,...,7.652886,108.0,88.0,77.110703,177.80000,24.4000,NaN,NaN,NaN,NaN
3,10000108,M,25,0,1,0,1,15.000000,29.000000,101.000000,...,NaN,88.0,88.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,10000117,F,48,0,1,1,1,16.928571,23.714286,102.533333,...,11.389456,106.0,73.0,50.407558,163.98875,18.5480,114.805556,71.847222,True,2.0

In [5]:
missing_values_prop = final_hosp_discharge_df.isnull().mean()
a = missing_values_prop*100.0
print("missings proportion:\n", a)

missings proportion:
 subject_id             0.000000
gender                 0.000000
anchor_age             0.000000
label                  0.000000
has_labs               0.000000
has_omr                0.000000
has_charte             0.000000
Anion_Gap_mean         4.647822
Bicarbonate_mean       4.639692
Chloride_mean          4.528578
Creatinine_mean        3.265671
Potassium_mean         4.479796
Sodium_mean            4.504187
Urea_Nitrogen_mean     3.718258
Glucose_mean           3.783300
Glucose_std           15.892030
Glucose_max            3.783300
Glucose_min            3.783300
weight_kg_mean        25.466815
height_cm_mean        36.767934
bmi_mean              41.922545
bp_sys_mean           31.995447
bp_dia_mean           31.995447
htn_any_mention       60.996233
htn_mention_count     60.996233
dtype: float64

In [13]:
final_hosp_discharge_df.to_csv("../data/processed/final_hosp_discharge.csv", index=False)

## Merge original dataset with radiology notes features

In [6]:
final_hosp_discharge_df = pd.read_csv("../data/processed/final_hosp_discharge.csv")
rad_compact_df = pd.read_csv("../data/processed/radiology_compact_summary.csv")

# Use LEFT JOIN to keep all rows from the hosp dataset
final_hosp_discharge_radio_df = pd.merge(
    final_hosp_discharge_df,
    rad_compact_df,
    on='subject_id',
    how='left'   # 👈 keeps all subjects from final_hosp_dataset_df
)

print(final_hosp_discharge_df.shape)
print(final_hosp_discharge_radio_df.shape)
final_hosp_discharge_radio_df.head()

(36899, 25)
(36899, 29)

,subject_id,gender,anchor_age,label,has_labs,has_omr,has_charte,Anion_Gap_mean,Bicarbonate_mean,Chloride_mean,...,height_cm_mean,bmi_mean,bp_sys_mean,bp_dia_mean,htn_any_mention,htn_mention_count,rad_any_mention,rad_mention_count,rad_first_mention_time,rad_last_mention_time
0,10000032,F,52,0,1,1,1,11.222222,25.388889,97.047619,...,152.40000,18.5375,106.166667,64.666667,True,3.0,NaN,NaN,NaN,NaN
1,10000068,F,19,0,0,0,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,10000084,M,72,0,1,1,1,12.833333,23.166667,100.666667,...,177.80000,24.4000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,10000108,M,25,0,1,0,1,15.000000,29.000000,101.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,10000117,F,48,0,1,1,1,16.928571,23.714286,102.533333,...,163.98875,18.5480,114.805556,71.847222,True,2.0,NaN,NaN,NaN,NaN

In [7]:
final_hosp_discharge_radio_df = final_hosp_discharge_radio_df.drop(columns=['rad_first_mention_time', 'rad_last_mention_time'])

In [8]:
final_hosp_discharge_radio_df.to_csv("../data/processed/final_hosp_discharge_radio.csv", index=False)